name: Build/release

on:
  workflow_dispatch:
    inputs:
      platform:
        description: '目标平台'
        required: true
        default: 'windows'
        type: choice
        options:
          - windows
          - linux
      arch:
        description: '平台架构'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86_64
          - x86
          - arm64
          - armv7l

          

jobs:
  BuildWindows:
    if: inputs.platform == 'windows'
    runs-on: 	windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: setup environment
        run: npm install pnpm -g
      - name: install libs
        run: pnpm install
      - name: build x86
        if: inputs.arch == 'x86'
        run: npm run build && pnpm electron-builder --win --ia32 --config --publish never
      - name: build x86_64
        if: inputs.arch == 'x86_64'
        run: npm run build && pnpm electron-builder --win --x64 --config --publish never
      - name: build arm64
        if: inputs.arch == 'arm64'
        run: npm run build && pnpm electron-builder --win --arm64 --config --publish never
      - name: build armv7l
        if: inputs.arch == 'armv7l'
        run: npm run build && pnpm electron-builder --win --armv7l --config --publish never
      - name: reg windows builds
        run: $EXE="node\$(Get-Childitem -Path dist -Include *.exe -Name -File)" ;
             $NAME=(get-item "dist\$(Get-Childitem -Path dist -Include *.exe -Name -File)").BaseName ;
             echo "EXE=$EXE" >> $GITHUB_ENV &&
             echo "NAME=$NAME" >> $GITHUB_ENV
      - name: Upload EXE RELEASE
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.NAME }}"
          path: "${{ env.EXE }}"
