name: Build/release

on:
  workflow_dispatch:
    inputs:
      platform:
        description: '目标平台'
        required: true
        default: 'windows'
        type: choice
        options:
          - windows
          - linux
      arch:
        description: '平台架构'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - x86_64
          - x86
          - arm64

          

jobs:
  BuildWindows:
    if: inputs.platform == 'windows'
    runs-on: 	windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: setup environment
        run: npm install pnpm -g && 
      - name: install libs
        run: pnpm install
